## Question 1


In [17]:
A = np.arange(0,7)

B = np.zeros((7,7), dtype= 'float32')

print(A+B)

[[0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]]


## Question 2

In [20]:
import numpy as np
from numpy.lib import stride_tricks

A = np.arange(6,12)

frame_length = 3

B = stride_tricks.sliding_window_view(A, frame_length)

print(B)


[[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]]


## Question 3

In [ ]:
Stochastic Gradient Descend (SGD) chooses up a "random" instance of training data at each step to calculate the gradient, 
which is significantly faster than Batch Gradient Descend because there is much less data to handle.
Therefore SGD saves time compared to Standard Gradient Descend. 

If the amount of data is large the batch gradient descend is expensive. Therefore the SGD is preffered for training large
data. So currently there is no better method than SGD. 


